openapi: "3.0.3"

info:
  title: "Swagger Sample API"
  version: "1.0.0"

paths:
  "/hello":
    get:
      summary: "Hello World API"
      description: "Get Hello World"
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              schema:
                type: string
                example: "Hello World"
