openapi: "3.0.3"
info:
  title: "Sample API"
  description: |
    # Features
    - Get samples.
    - Create samples.

  contact:
    name: "Sample Name"
    url: "https://no-server.com/sample"
    email: "sample@example.com"
  license:
    name: "Sample License"
  version: "1.0.0"

paths:
  "/message":
    get:
      summary: "Sample API get operation"
      description: "Sample API get operation"
      responses:
        "200":
          description: "Success operation"
          content:
            application/json:
              schema:
                type: string
                example: "Hello World!"
