openapi: "3.0.3"

info:
  title: "Swagger Sample API"
  description: |
    # Features
    - Get Hello World
    - Other Brilliant API
  termsOfService: "https://www.example.com/sample-terms-of-service"
  contact:
    name: "Sample API team"
    url: "https://www.example.com/sample-support"
    email: "sample-support@example.com"
  license:
    name: "Sample License"
    url: "https://www.example.com/sample-license"
  version: "1.0.0"

servers:
  - url: "https://www.example.dev.com/{version}"
    description: "Development Environment"
    variables:
      version:
        description: "version"
        enum: ["v1", "v2"]
        default: "v1"
  - url: "https://www.example.stg.com/{version}"
    description: "Staging Environment"
    variables:
      version:
        description: "version"
        enum: ["v1", "v2"]
        default: "v1"
  - url: "https://www.example.com/{version}"
    description: "Development Environment"
    variables:
      version:
        description: "version"
        enum: ["v1", "v2"]
        default: "v1"

paths:
  "/hello":
    get:
      summary: "Hello World API"
      description: "Get Hello World"
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              schema:
                type: string
                example: "Hello World"
